export const MONITORING_AUTO_REFRESH_MS = 60_000;
export const MONITORING_HISTORY_HOURS = 24;
export const MONITORING_HISTORY_CAPACITY = 1440;
export const MONITORING_RECENT_ROWS = 10;
export const MONITORING_SPARKLINE_POINTS = 240;
